apiVersion: v1
kind: ConfigMap
metadata:
  name: oficina-billing-service-config
  labels:
    app.kubernetes.io/name: oficina-billing-service
    app.kubernetes.io/part-of: oficina
    app.kubernetes.io/component: service
data:
  DEPLOYMENT_ENVIRONMENT: lab
  AWS_REGION: us-east-1
  AWS_DEFAULT_REGION: us-east-1
  OFICINA_PROJECT_NAME: oficina
  OFICINA_ENVIRONMENT_NAME: lab
  OFICINA_ENVIRONMENT: lab
  OFICINA_SECRET_PREFIX: oficina/lab
  OFICINA_AUTH_ISSUER: OFICINA_AUTH_ISSUER_PLACEHOLDER
  OFICINA_AUTH_AUDIENCE: oficina-billing-service
  MP_JWT_VERIFY_PUBLICKEY_LOCATION: OFICINA_AUTH_JWKS_URI_PLACEHOLDER
  OTEL_SERVICE_NAME: oficina-billing-service
  OTEL_RESOURCE_ATTRIBUTES: service.namespace=oficina,deployment.environment=lab
  OTEL_EXPORTER_OTLP_ENDPOINT: http://nr-k8s-otel-collector-gateway.newrelic.svc.cluster.local:4317
  OTEL_EXPORTER_OTLP_PROTOCOL: grpc
  QUARKUS_OTEL_TRACES_EXPORTER: cdi
  OTEL_METRICS_EXPORTER: none
  OTEL_LOGS_EXPORTER: none
  OFICINA_OBSERVABILITY_ENABLED: "true"
  OFICINA_OBSERVABILITY_JSON_LOGS_ENABLED: "true"
  OFICINA_OBSERVABILITY_METRICS_ENABLED: "true"
  OFICINA_OBSERVABILITY_TRACING_ENABLED: "true"
  QUARKUS_DATASOURCE_REACTIVE_POSTGRESQL_SSL_MODE: require
  QUARKUS_DATASOURCE_REACTIVE_TRUST_ALL: "true"
