apiVersion: v1
kind: ServiceAccount
metadata:
  name: oficina-execution-service
  labels:
    app.kubernetes.io/name: oficina-execution-service
    app.kubernetes.io/part-of: oficina
    app.kubernetes.io/component: service
