apiVersion: v1
kind: Service
metadata:
  name: oficina-execution-service
  labels:
    app.kubernetes.io/name: oficina-execution-service
    app.kubernetes.io/part-of: oficina
    app.kubernetes.io/component: service
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: oficina-execution-service
  ports:
    - name: http
      port: 8080
      targetPort: http
